package com.lwjlol.ormkv.annotation.compiler

import com.lwjlol.ormkv.OrmKvHandler
import com.lwjlol.ormkv.annotation.ColumnInfo
import com.lwjlol.ormkv.annotation.Entity
import com.lwjlol.ormkv.annotation.Ignore
import com.squareup.kotlinpoet.*
import java.io.File
import javax.annotation.processing.*
import javax.lang.model.SourceVersion
import javax.lang.model.element.Element
import javax.lang.model.element.Modifier
import javax.lang.model.element.TypeElement
import javax.tools.Diagnostic

/**
 * @author luwenjie on 2019-08-11 19:17:41
 */
// @AutoService(value = [Process::class])
@Suppress("DEPRECATION")
@SupportedSourceVersion(value = SourceVersion.RELEASE_8)
@SupportedAnnotationTypes(value = ["com.lwjlol.ormkv.annotation.Entity", "com.lwjlol.ormkv.annotation.ColumnInfo", "com.lwjlol.ormkv.annotation.Ignore"])
class KaptOrmkvProcessor : AbstractProcessor() {
    private var messager: Messager? = null
    override fun init(processingEnv: ProcessingEnvironment?) {
        super.init(processingEnv)
        messager = processingEnv?.messager
    }

    private fun print(text: String) {
        if (!LOG) return
        messager?.printMessage(Diagnostic.Kind.NOTE, text)
        println("CCSharePreProcessor--- $text")
    }

    override fun process(
        annotations: MutableSet<out TypeElement>,
        roundEnv: RoundEnvironment
    ): Boolean {
        val elementUtils = processingEnv.elementUtils
        print("process")
        annotations.forEach {
            print(it::class.java.name)
        }

        roundEnv.getElementsAnnotatedWith(Entity::class.java)
            .forEach { element ->
                if (element.kind.isClass) {
                    val entity = element.getAnnotation(Entity::class.java)
                    val allMembers = element.enclosedElements
                    val className = element.simpleName.toString()
                    val packageName = elementUtils.getPackageOf(element).toString()
                    generateClass(className, packageName, allMembers, entity)
                }
            }
        return true
    }

    private fun generateClass(
        className: String,
        packageName: String,
        allMembers: List<Element>,
        entity: Entity
    ) {
        var name = entity.className
        val prefix = entity.prefix
        val generatePackageName = if (entity.className.contains('.')) {
            name = entity.className.substringAfterLast('.')
            entity.className.substringBeforeLast('.')
        } else {
            packageName
        }
        if (name.isEmpty()) {
            name = className
        }
        val fileName = if (entity.className.isNotEmpty()) name else "${name}$END_FIX"
        val typeSpec = TypeSpec.classBuilder(fileName)
            .addKdoc("this class is generated by https://github.com/lwj1994/ormkv for [$packageName.$className], Please don't modify it!")

        if (entity.handler.isEmpty()) {
            return
        }
        typeSpec.addProperty(
            PropertySpec.builder(
                HANDLER,
                OrmKvHandler::class,
                KModifier.PRIVATE
            ).initializer(entity.handler).build()
        )
        // clear code
        val clearCode = StringBuilder()
        val initCode = StringBuilder()
        val toStringCode = StringBuilder()
        val toModelCode = StringBuilder()
        val updateCode = StringBuilder()

        var toModelError = false
        allMembers.forEachIndexed { _, member ->
            if (member.kind.isField && !member.modifiers.contains(Modifier.STATIC)) {
                val ignore: Ignore? = member.getAnnotation(Ignore::class.java)
                val spColumnInfo: ColumnInfo? = member.getAnnotation(ColumnInfo::class.java)
                var defaultValue = spColumnInfo?.defaultValue ?: ""
                val columnName = spColumnInfo?.name ?: ""
                val clear = spColumnInfo?.enableReset ?: true
                val memberTypeName = member.asType().asTypeName()
                val valueName = "_${member.simpleName}"
                val propertyName = member.simpleName.toString()
                val typeName =
                    when {
                        memberTypeName.toString().contains("String") -> ClassName(
                            "kotlin",
                            "String"
                        )
                        memberTypeName.toString() == "kotlin.Array<kotlin.Byte>" -> {
                            ClassName("kotlin", "ByteArray")
                        }

                        else -> memberTypeName
                    }

                print("propertyName = $propertyName, memberTypeName = $memberTypeName, typeName = $typeName")

                val paramType = typeName.toString()
                val keyUnitName = columnName.ifEmpty { propertyName }
                val keyName = if (prefix.isNotEmpty()) "${prefix}_$keyUnitName" else keyUnitName

                val getName = when {
                    paramType.contains("String") -> {
                        defaultValue = defaultValue.ifEmpty { "\"\"" }
                        "get(\"$keyName\", $defaultValue) as String"
                    }
                    paramType.contains("Boolean") -> {
                        defaultValue = defaultValue.ifEmpty { "false" }
                        "get(\"$keyName\", $defaultValue) as Boolean"
                    }
                    paramType.contains("Int") -> {
                        defaultValue = defaultValue.ifEmpty { "0" }
                        "get(\"$keyName\", $defaultValue) as Int"
                    }
                    paramType.contains("Long") -> {
                        defaultValue = defaultValue.ifEmpty { "0L" }
                        if (!defaultValue.endsWith('L')) {
                            defaultValue = "${defaultValue}L"
                        }
                        "get(\"$keyName\", $defaultValue) as Long"
                    }
                    paramType.contains("Float") -> {
                        defaultValue = defaultValue.ifEmpty { "0F" }
                        if (!defaultValue.endsWith('F')) {
                            defaultValue = "${defaultValue}F"
                        }
                        "get(\"$keyName\", $defaultValue) as Float"
                    }
                    paramType.contains("ByteArray") -> {
                        defaultValue = defaultValue.ifEmpty { "ByteArray(0)" }
                        "get(\"$keyName\", $defaultValue) as ByteArray"
                    }
                    else -> {
                        defaultValue = "error"
                        "unsupported"
                    }
                }

                if (ignore != null && !toModelError) {
                    if (defaultValue == "error") {
                        toModelError = true
                        return@forEachIndexed
                    }
//                    if (paramType.contains("String")) {
//                        toModelCode.append("|$propertyName = \"$defaultValue\", \n")
//                    } else {
                        toModelCode.append("|$propertyName = $defaultValue, \n")
//                    }
                    return@forEachIndexed
                }

                val setName = """put("$keyName", value)"""
                typeSpec.addProperty(
                    PropertySpec.builder(valueName, typeName.copy(true))
                        .initializer("null")
                        .addModifiers(KModifier.PRIVATE)
                        .mutable(true)
                        .build()
                )
                typeSpec.addProperty(
                    PropertySpec.builder(propertyName, typeName)
                        .mutable(true)
                        .getter(
                            FunSpec.getterBuilder()
                                .addCode(
                                    """
                                    |if ($valueName == null) {
                                    |   $valueName = $HANDLER.$getName
                                    |}
                                    |return $valueName!!
                                    |
                                    """.trimMargin()
                                )
                                .build()
                        )
                        .setter(
                            FunSpec.setterBuilder().addParameter("value", typeName).addCode(
                                """
                            |$valueName = value
                            |$HANDLER.$setName
                            |
                                """.trimMargin()
                            ).build()
                        )
                        .build()
                )
                toStringCode.append("|$propertyName = $$propertyName\n")
                toModelCode.append("|$propertyName = $propertyName, \n")
                updateCode.append("|$propertyName = model.$propertyName\n")
                initCode.append("|$valueName = $HANDLER.$getName\n")
                if (clear) {
//                    if (typeName.toString().contains("String")) {
//                        clearCode.append("$propertyName = \"\"\"$defaultValue\"\"\" \n")
//                    } else {
                        clearCode.append("$propertyName = $defaultValue \n")
//                    }
                }
            }
        }

        typeSpec.addFunction(
            FunSpec.builder("refresh")
                .addCode(
                    """
                       $initCode 
                    """.trimMargin()
                ).build()
        )

        // add reset()
        typeSpec.addFunction(
            FunSpec.builder("reset")
                .addCode(
                    """
              |$clearCode
                    """.trimMargin()
                )
                .build()
        ).addToString("return \"\"\"$toStringCode\"\"\".trimMargin()")
            .addUpdate(updateCode.toString().trimMargin(), ClassName(packageName, className))
        if (!toModelError) {
            typeSpec.addToModel(toModelCode.toString(), "$packageName.$className")
        }

        // write file
        val file = FileSpec.builder(generatePackageName, fileName).addType(typeSpec.build()).build()
        val kaptKotlinGeneratedDir = processingEnv.options[KAPT_KOTLIN_GENERATED_OPTION_NAME]
        file.writeTo(File(kaptKotlinGeneratedDir!!))
    }

    private fun TypeSpec.Builder.addToString(code: String): TypeSpec.Builder {
        return addFunction(
            FunSpec.builder("toString")
                .returns(String::class)
                .addModifiers(KModifier.OVERRIDE)
                .addCode(code)
                .build()
        )
    }

    private fun TypeSpec.Builder.addToModel(code: String, className: String): TypeSpec.Builder {
        return addFunction(
            FunSpec.builder("toModel")
                .returns(ClassName.bestGuess(className))
                .addCode(
                    """
                    |return $className(
                    ${code.trim('\n').trim(' ').trim(',')})             
                    """.trimMargin()
                )
                .build()
        )
    }

    private fun TypeSpec.Builder.addUpdate(code: String, typeName: TypeName): TypeSpec.Builder {
        return addFunction(
            FunSpec.builder("update")
                .addParameter(ParameterSpec.builder("model", typeName).build())
                .addCode(code)
                .build()
        )
    }

    companion object {
        const val KAPT_KOTLIN_GENERATED_OPTION_NAME = "kapt.kotlin.generated"
        private const val TAG = "OrmkvProcessor"
        private const val END_FIX = "Registry"
        private const val LOG = false
        private const val HANDLER = "kvHandler"
    }
}
